--liquibase formatted sql

-- changeset Gleb:1
CREATE TABLE IF NOT EXISTS clients.customer
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name        VARCHAR(50)  NOT NULL,
    second_name       VARCHAR(50)  NOT NULL,
    email             VARCHAR(50)  NOT NULL UNIQUE,
    phone_number      VARCHAR(20)  NOT NULL UNIQUE,
    address           VARCHAR(100) NOT NULL,
    registration_time TIMESTAMP    NOT NULL,
    password          varchar(255) not null
);