version: '3.8'

services:
  app:
    image: '4d501b6c1ce8'
    container_name: UserMicroservice
    expose:
      - '8000'
    ports:
      - '8000:8000'
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_URL=jdbc:postgresql://db:5432/client_db
      - SPRING_PROFILES_ACTIVE=debug
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: db
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=client_db
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d