services:
  product-app:
    build:
      context: .
      dockerfile: Dockerfile-product
    container_name: ProductMicroservice
    expose:
      - '8002'
    ports:
      - '8002:8002'
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_URL=jdbc:postgresql://product-db:5432/product_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9094,kafka-3:9096
      - SPRING_PROFILES_ACTIVE=debug
    networks:
      - my-network
    depends_on:
      - product-db

  product-db:
    image: 'postgres'
    container_name: product-db
    expose:
      - '5432'
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=product_db
    volumes:
      - ./product-db-init:/docker-entrypoint-initdb.d
    networks:
      - my-network

networks:
  my-network:
    external: true