CREATE TABLE IF NOT EXISTS product
(
    id         BIGINT generated by default as identity PRIMARY KEY,
    name       VARCHAR(255)   NOT NULL,
    quantity   INT            NOT NULL,
    price      DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO product (name, quantity, price)
VALUES
    ('Product 1', 10, 19.99),
    ('Product 2', 5, 9.50),
    ('Product 3', 20, 15.75),
    ('Product 4', 8, 25.00),
    ('Product 5', 12, 30.99);